### ISSUE TITLE
Drop additional map keys instead of rejecting requests.

### ISSUE THREAD

**Issue by sarnowski** [zalando-stups/swagger1st#16]
If a requests with an undefined key comes in, drop it silently instead of rejecting the request as this is better for compatiblity.

This should be an option in the parser module `:allow-undefined-keys`.

**Comment by hjacobs** [comment]
I would personally not like to have this option on by default, having optional keys and "allow-undefined-keys" could e.g. lead to potential "typo" errors. Obviously it may make sense to enable the option to allow for seamless migration from API version "n" to "n+1".

**Comment by sarnowski** [comment]
agree, it should be strict by default

**Comment by sarnowski** [comment]
Usage example during app setup:

``` clojure
(-> (s1st/context ...)
    ....
    (s1st/parser :allow-undefined-keys true)
    ....
    )
```
