### ISSUE TITLE
Implement "collectionFormat" for parameter parsing

### ISSUE THREAD

**Issue by sarnowski** [zalando-stups/swagger1st#23]
> Determines the format of the array if type array is used. Possible values are: <ul><li>`csv` - comma separated values `foo,bar`. <li>`ssv` - space separated values `foo bar`. <li>`tsv` - tab separated values `foo\tbar`. <li>`pipes` - pipe separated values <code>foo&#124;bar</code>. <li>`multi` - corresponds to multiple parameter instances instead of multiple values for a single instance `foo=bar&foo=baz`. This is valid only for parameters [`in`](#parameterIn) "query" or "formData". </ul> Default value is `csv`.

**Comment by avaczi** [comment]
Do I understand correctly that the following error:

```
{
  "message": "Value \"a,s,d\" in query->p_fields (required) cannot be used as type 'array' because it is not an array.",
  "details": null
}
```

is because of this?  (When specifying `collectionFormat: multi`, I get an exception:

```
java.lang.ClassCastException: java.lang.String cannot be cast to clojure.lang.Associative
```

).  If yes, is there any other workaround than specifying the parameter as `string` and silently expect a CSV list (for example)?

**Comment by sarnowski** [comment]
Unfortunately, you hit the not-implemented-yet feature. Yes, the error message comes exactly because this is not implemented. I am not sure about the last error message about Associative.

In any case, the best workaround is to actually implement the functionality.  It shouldn't be too hard (just not as straight-forward than the rest, thats why its missing as it had no priority yet).

That said, one has to recognize that the last case `multi` is different from the others as the others are only different delimiters and `multi` is another way of passing the arguments.

**Comment by sebastianpoeplau** [comment]
I'll give the implementation a try...
