### ISSUE TITLE
Parsing JSON body parameters corrupts keys containing slashes

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/swagger1st#26]
Parsing JSON body parameters uses the "read-json" function which keywordizes JSON keys (https://github.com/sarnowski/swagger1st/blob/master/src/io/sarnowski/swagger1st/parser.clj#L89), this corrupts data containing keys such as "8080/tcp" or "key/with/slashes".

Pier One has a serious bug (https://github.com/zalando-stups/pierone/issues/9) because of this behavior.

The TODO comment already mentions that the JSON body parsing behavior should be configurable.

**Comment by sarnowski** [comment]
Solution should be, to be able to overwrite the standard JSON parser.
