### ISSUE TITLE
Erroneous DateTime serialization

### ISSUE THREAD

**Issue by prayerslayer** [zalando-stups/swagger1st#35]
Introduced by me. Sorry.

Fix with PR is on the way.

**Comment by lasomethingsomething** [comment]
@sebastianpoeplau @harti2006 Hi, @prayerslayer isn't sure now if he fixed everything in the commit because the issue's +1 year old ... you can probably close?

**Comment by sebastianpoeplau** [comment]
@prayerslayer's fix is in master and we haven't seen issues with date serialization recently, so I guess we can close the issue.
