### ISSUE TITLE
Old Leiningen template

### ISSUE THREAD

**Issue by immoh** [zalando-stups/swagger1st#67]
Running `lein new swagger1st myproject` as instrcuted in README finds [[swagger1st/lein-template "0.15.1"] on Clojars](https://clojars.org/swagger1st/lein-template/versions/0.15.1) and generates a project that has `[io.sarnowski/swagger1st "0.15.0"]` as dependency.

**Comment by sebastianpoeplau** [comment]
Good point, thanks. I think the code has been updated, so we should be good with just releasing a new version of the template.

**Comment by lasomethingsomething** [comment]
Hi @sebastianpoeplau, any news on this issue or can we close?

**Comment by sebastianpoeplau** [comment]
@LappleApple I'm afraid we don't have access to the Clojars account that hosts the template. @sarnowski, would you mind giving us access?

**Comment by immoh** [comment]
Why was this closed?

**Comment by LappleApple** [comment]
@immoh Because @sarnowski provided the information requested.

**Comment by harti2006** [comment]
I upgraded everything and released it to clojars:
https://clojars.org/swagger1st/lein-template/versions/0.25.0
